# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pixel}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathaniel Jones"]
  s.date = %q{2010-06-24}
  s.description = %q{Quickly calculate the new dimensions of a resized image by giving it the original dimensions, and how many pixels wide or tall you need your new image to be}
  s.email = %q{nathaniel@pointeractive.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "lib/pixel.rb",
     "lib/pixel/extensions.rb",
     "lib/pixel/pixel.rb",
     "pixel.gemspec",
     "spec/integer_spec.rb",
     "spec/pixel_spec.rb"
  ]
  s.homepage = %q{http://github.com/nthj/pixel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby extension for calculating the new dimensions of a resized image}
  s.test_files = [
    "spec/integer_spec.rb",
     "spec/pixel_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

